### ISSUE TITLE
Package turbopoweripro cannot be compiled

### ISSUE THREAD

**Issue by JohnML1** [silvioprog/lazwebsolutions#3]
Hi,

A) I don't know the wright place to post this 

B) I cannot compile this package an i assume the reason is:

unit Iphttpbroker.pas

Lazarus 1.7 r51418 FPC 2.6.4 i386-win32-win32/win64

error:

Kompiliere Package TurboPowerIPro 1.0: Exit code 1, Fehler: 3
iphttpbroker.pas(86,11) Error: identifier idents no member "AllowRedirect"
iphttpbroker.pas(87,11) Error: identifier idents no member "MaxRedirects"
iphttpbroker.pas(130,15) Error: identifier idents no member "IsRedirect"

**Comment by silvioprog** [comment]
Hello @JohnML1 , the `iphttpbroker` unit was added recently in the Lazarus components. If you are using a stable version of Lazarusm, get and apply all patches sent in this issue: http://bugs.freepascal.org/view.php?id=29483.
